# Generated by Django 5.0.7 on 2024-07-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_option_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
